avatar: https://unavatar.io/nexmoe?ttl=21 # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
    path: https://i.pximg.net/img-master/img/2025/03/05/11/01/05/127882496_p0_master1200.jpg
favicon:
    href: https://unavatar.io/nexmoe?ttl=21 # 网站图标
    type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
    globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能
    wordCount: false # 是否开启文章字数统计 (true, false)

imageCDN: # 图片 CDN 功能
    enable: false # 开启该功能
    origin: /../../images/ # 图片原始目录
    to: https://nexmoe.com/images/ # 图片 CDN 域名

# 自定义样式，启用后可在站点的source文件夹下新建custom.css自定义站点样式
customStyles:
    - custom.css

# 附加图标库 使用说明：https://docs.nexmoe.com/config/icon
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
    回到首页:
        - /
        - icon-home
    文章归档:
        - /archive.html
        - icon-container
    我的朋友:
        - /PY.html
    给我赞助:
        - /donate.html
        - icon-coffee
    关于博主:
        - /about.html
        - icon-info-circle

widgets:
    - name: search
      enable: true
      options:
          search:
              type: engine # 可选engine（用搜索引擎搜索）、swiftype、或local（本地搜索）
              url: https://cn.bing.com/search?q=site:nexmoe.com # 搜索引擎地址，在type为swiftype时无效 e.g:https://www.google.com/search?q={你的博客链接}
              id: <swiftype-id> # swiftype的id，见启用教程。在type为engine时无效
    - name: social
      enable: true
      options:
          social:
              QQ群:
                  - https://nexmoe.com/3145B9F.html
                  - icon-QQ
                  - rgb(249, 174, 8)
                  - rgba(249, 174, 8, .1)
              哔哩哔哩:
                  - https://space.bilibili.com/20238211
                  - icon-bilibili
                  - rgb(231, 106, 141)
                  - rgba(231, 106, 141, .1)
              GitHub:
                  - https://github.com/nexmoe/
                  - icon-github
                  - rgb(25, 23, 23)
                  - rgba(25, 23, 23, .1)
              Twitter:
                  - https://twitter.com/nexmoe
                  - icon-twitter
                  - rgb(59, 151, 239)
                  - rgba(59, 151, 239, .1)
              RSS:
                  - https://nexmoe.com/atom.xml
                  - icon-rss
                  - rgb(247, 132, 34)
                  - rgba(247, 132, 34, .1)
    - name: category
      enable: false
    - name: tagcloud
      enable: false
      options:
          maxTagcloud: 17 # 标签云组件显示的标签数量，0 表示不限制
    - name: hitokoto # 一言 widget
      enable: false
      options:
          widgetHitokoto: # 一言组件
              loading_placeholder: '🚀 获取中...' # 正在一言时的占位符
              loading_error_placeholder: '🐞 获取失败...' # 加载一言失败时的占位符
              category: # 一言句子类型（可选），不配置的话随机获取，详见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    - name: archive #settings: widgetAchive
      enable: false
      options:
          widgetAchive: #文章归档组件
              archive_type: 'year' #按月展示还是按年展示
              show_count: true #是否展示数量
    - name: recent_posts
      enable: false
    - name: link #settings: widgetLink
      enable: false
      options:
          widgetLink: #链接组件
              - title: 小舒同学
                img: https://xsm.nexmoe.com/images/Infinite/Snipaste_2022-05-18_20-46-50.png
                link: https://xiaoshu.app/
              - title: 折影轻梦
                img: https://nexmoe.com/images/avatar.png
                link: https://nexmoe.com/

copyTip: false # 自定义复制版权文案,使用 %url 代替当前页面URL, 修改为false禁用

slotHead: |
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-4D4ZJ9G024"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag("js", new Date());

      gtag("config", "G-4D4ZJ9G024");
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/atom-one-dark.min.css">

slotFooter: |
    <script src='https://sentry.mixcm.com/js-sdk-loader/affb515ef7b517cb3fc0dc63d65a9fc2.min.js' crossorigin="anonymous"></script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2058306854838448" crossorigin="anonymous"></script>

# 自定义侧边栏尾部内容
slotSidebar: |
    <br><a target="_blank" href="https://beian.miit.gov.cn/">鄂ICP备2020018486号</a>
    <br><a target="_blank" href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral">
    <img src="https://i.dawnlab.me/c0268c1e6cfd0863d6ba35be1575941a.png" width="150px"></a>

# 评论框插槽
slotComment: |
    <script src="https://giscus.app/client.js"
        data-repo="nexmoe/nexmoe.com"
        data-repo-id="R_kgDOJI1XUA"
        data-category="General"
        data-category-id="DIC_kwDOJI1XUM4CU1nn"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
    </script>

slotCopyright: |
    <strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可

slotArticleEnd: ~